language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: ZPg2hxMgoFgL9ByaALk+oCOa3EV6z1I6xrqMHhLEx5JVyRcLZYKbz6hbv/wOwizh+LiFN9Lg49bkvbA5c0ouQ82/ghSpinrvgL8hmNucueZ/LPIKbfXn0sKbroJORnzMsA+ycBfZ6w1XS8BVSRpDUpbBqN2tO9JnzofcyUbL7QHSUiWp08umOcMGy2K05mOlx11gGWbS6RKuvkL0RcGyRRL7RO/YN4By7ky4lc6J5ZyQex/T/B2gPWlIhmoUfSbk0vHs6xeXHW8+Cgfjk5Wvb3nEu4z+hpeG3KbgvYyd1G8hYqwd6eS6p6Ntk8jd8/UHJUOmNAFCEk+c4piKk4VOClL48GmbgWkerN2xinSXhg1DOt190YzZeKo3oivYLWPsejs+MRYJ/zCEd2X3hVL62eR57ZMynFp233TQdjHiq4l3XwwZtnFrynh2slTAswJl5SSu1Sye0krlY814BoeWBSrPAeBESXVqV6rtNmd0oMvAqTuqqzA4n4bxFYSJvm+zkqF9AhXXlUm/a5FompNPzIgZDIchBDKBRl9tWHIYsDmU8K46S2D7lApoasgou8Ez5A7PDVKMu4gOY/9QqQlCM3N1FWfpaNFtAsPjHjqJs5Pt5/Hl05yeQ1ao0zLUOwtlQkvcHpuK7tgKuzW6BYSpjvYiQmxi8wT+XarvwIgSRC0=
  on:
    tags: true
    node: '9.0'
